package sap_api_output_formatter

type CustomerReturn struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	APISchema     string `json:"api_schema"`
	SalesOrder    string `json:"sales_order"`
	Deleted       bool   `json:"deleted"`
}

type Header struct {
	CustomerReturn                string `json:"CustomerReturn"`
	CustomerReturnType            string `json:"CustomerReturnType"`
	SalesOrganization             string `json:"SalesOrganization"`
	DistributionChannel           string `json:"DistributionChannel"`
	OrganizationDivision          string `json:"OrganizationDivision"`
	SalesGroup                    string `json:"SalesGroup"`
	SalesOffice                   string `json:"SalesOffice"`
	SalesDistrict                 string `json:"SalesDistrict"`
	SoldToParty                   string `json:"SoldToParty"`
	CreationDate                  string `json:"CreationDate"`
	CreatedByUser                 string `json:"CreatedByUser"`
	LastChangeDate                string `json:"LastChangeDate"`
	SenderBusinessSystemName      string `json:"SenderBusinessSystemName"`
	LastChangeDateTime            string `json:"LastChangeDateTime"`
	PurchaseOrderByCustomer       string `json:"PurchaseOrderByCustomer"`
	CustomerPurchaseOrderType     string `json:"CustomerPurchaseOrderType"`
	CustomerPurchaseOrderDate     string `json:"CustomerPurchaseOrderDate"`
	CustomerReturnDate            string `json:"CustomerReturnDate"`
	TotalNetAmount                string `json:"TotalNetAmount"`
	TransactionCurrency           string `json:"TransactionCurrency"`
	SDDocumentReason              string `json:"SDDocumentReason"`
	PricingDate                   string `json:"PricingDate"`
	RequestedDeliveryDate         string `json:"RequestedDeliveryDate"`
	ShippingType                  string `json:"ShippingType"`
	HeaderBillingBlockReason      string `json:"HeaderBillingBlockReason"`
	DeliveryBlockReason           string `json:"DeliveryBlockReason"`
	IncotermsClassification       string `json:"IncotermsClassification"`
	IncotermsTransferLocation     string `json:"IncotermsTransferLocation"`
	IncotermsLocation1            string `json:"IncotermsLocation1"`
	IncotermsLocation2            string `json:"IncotermsLocation2"`
	IncotermsVersion              string `json:"IncotermsVersion"`
	CustomerPaymentTerms          string `json:"CustomerPaymentTerms"`
	PaymentMethod                 string `json:"PaymentMethod"`
	CustomerTaxClassification1    string `json:"CustomerTaxClassification1"`
	CustomerTaxClassification2    string `json:"CustomerTaxClassification2"`
	CustomerTaxClassification3    string `json:"CustomerTaxClassification3"`
	CustomerTaxClassification4    string `json:"CustomerTaxClassification4"`
	CustomerTaxClassification5    string `json:"CustomerTaxClassification5"`
	CustomerTaxClassification6    string `json:"CustomerTaxClassification6"`
	CustomerTaxClassification7    string `json:"CustomerTaxClassification7"`
	CustomerTaxClassification8    string `json:"CustomerTaxClassification8"`
	CustomerTaxClassification9    string `json:"CustomerTaxClassification9"`
	RetsMgmtProcess               string `json:"RetsMgmtProcess"`
	ReferenceSDDocument           string `json:"ReferenceSDDocument"`
	ReferenceSDDocumentCategory   string `json:"ReferenceSDDocumentCategory"`
	CustomerReturnApprovalReason  string `json:"CustomerReturnApprovalReason"`
	SalesDocApprovalStatus        string `json:"SalesDocApprovalStatus"`
	RetsMgmtLogProcgStatus        string `json:"RetsMgmtLogProcgStatus"`
	RetsMgmtCompnProcgStatus      string `json:"RetsMgmtCompnProcgStatus"`
	RetsMgmtProcessingStatus      string `json:"RetsMgmtProcessingStatus"`
	OverallSDProcessStatus        string `json:"OverallSDProcessStatus"`
	TotalCreditCheckStatus        string `json:"TotalCreditCheckStatus"`
	OverallSDDocumentRejectionSts string `json:"OverallSDDocumentRejectionSts"`
	ToItem                        string `json:"to_Item"`
	ToHeaderPartner               string `json:"to_Partner"`
}

type Item struct {
	CustomerReturn                 string `json:"CustomerReturn"`
	CustomerReturnItem             string `json:"CustomerReturnItem"`
	HigherLevelItem                string `json:"HigherLevelItem"`
	CustomerReturnItemCategory     string `json:"CustomerReturnItemCategory"`
	CustomerReturnItemText         string `json:"CustomerReturnItemText"`
	PurchaseOrderByCustomer        string `json:"PurchaseOrderByCustomer"`
	Material                       string `json:"Material"`
	MaterialByCustomer             string `json:"MaterialByCustomer"`
	RequestedQuantity              string `json:"RequestedQuantity"`
	RequestedQuantityUnit          string `json:"RequestedQuantityUnit"`
	ItemGrossWeight                string `json:"ItemGrossWeight"`
	ItemNetWeight                  string `json:"ItemNetWeight"`
	ItemWeightUnit                 string `json:"ItemWeightUnit"`
	ItemVolume                     string `json:"ItemVolume"`
	ItemVolumeUnit                 string `json:"ItemVolumeUnit"`
	TransactionCurrency            string `json:"TransactionCurrency"`
	NetAmount                      string `json:"NetAmount"`
	MaterialGroup                  string `json:"MaterialGroup"`
	Batch                          string `json:"Batch"`
	ProductionPlant                string `json:"ProductionPlant"`
	StorageLocation                string `json:"StorageLocation"`
	ShippingPoint                  string `json:"ShippingPoint"`
	ShippingType                   string `json:"ShippingType"`
	DeliveryPriority               string `json:"DeliveryPriority"`
	IncotermsClassification        string `json:"IncotermsClassification"`
	IncotermsTransferLocation      string `json:"IncotermsTransferLocation"`
	IncotermsLocation1             string `json:"IncotermsLocation1"`
	IncotermsLocation2             string `json:"IncotermsLocation2"`
	CustomerPaymentTerms           string `json:"CustomerPaymentTerms"`
	ProductTaxClassification1      string `json:"ProductTaxClassification1"`
	ProductTaxClassification2      string `json:"ProductTaxClassification2"`
	ProductTaxClassification3      string `json:"ProductTaxClassification3"`
	ProductTaxClassification4      string `json:"ProductTaxClassification4"`
	ProductTaxClassification5      string `json:"ProductTaxClassification5"`
	ProductTaxClassification6      string `json:"ProductTaxClassification6"`
	ProductTaxClassification7      string `json:"ProductTaxClassification7"`
	ProductTaxClassification8      string `json:"ProductTaxClassification8"`
	ProductTaxClassification9      string `json:"ProductTaxClassification9"`
	SalesDocumentRjcnReason        string `json:"SalesDocumentRjcnReason"`
	ItemBillingBlockReason         string `json:"ItemBillingBlockReason"`
	ProfitCenter                   string `json:"ProfitCenter"`
	RetsMgmtProcess                string `json:"RetsMgmtProcess"`
	RetsMgmtProcessItem            string `json:"RetsMgmtProcessItem"`
	ReturnReason                   string `json:"ReturnReason"`
	RetsMgmtProcessingBlock        string `json:"RetsMgmtProcessingBlock"`
	CustRetItmFollowUpActivity     string `json:"CustRetItmFollowUpActivity"`
	ReturnsMaterialHasBeenReceived string `json:"ReturnsMaterialHasBeenReceived"`
	ReturnsRefundType              string `json:"ReturnsRefundType"`
	ReturnsRefundProcgMode         string `json:"ReturnsRefundProcgMode"`
	ReturnsRefundExtent            string `json:"ReturnsRefundExtent"`
	PrelimRefundIsDetermined       string `json:"PrelimRefundIsDetermined"`
	ReturnsRefundRjcnReason        string `json:"ReturnsRefundRjcnReason"`
	ReplacementMaterial            string `json:"ReplacementMaterial"`
	ReplacementMaterialQuantity    string `json:"ReplacementMaterialQuantity"`
	ReplacementMaterialQtyUnit     string `json:"ReplacementMaterialQtyUnit"`
	ReplacementMaterialIsRequested string `json:"ReplacementMaterialIsRequested"`
	ReplacementMatlSupplyingPlant  string `json:"ReplacementMatlSupplyingPlant"`
	NextPlantForFollowUpActivity   string `json:"NextPlantForFollowUpActivity"`
	ReturnsTransshipmentPlant      string `json:"ReturnsTransshipmentPlant"`
	Supplier                       string `json:"Supplier"`
	SupplierRetMatlAuthzn          string `json:"SupplierRetMatlAuthzn"`
	SuplrRetMatlAuthznIsRequired   string `json:"SuplrRetMatlAuthznIsRequired"`
	CustomerRetMatlInspResultCode  string `json:"CustomerRetMatlInspResultCode"`
	NextFllwUpActivityForMatlInsp  string `json:"NextFllwUpActivityForMatlInsp"`
	RetMatlInspResultCode          string `json:"RetMatlInspResultCode"`
	ProductIsInspectedAtCustSite   string `json:"ProductIsInspectedAtCustSite"`
	CustRetMatlAuthzn              string `json:"CustRetMatlAuthzn"`
	CRMLogicalSystem               string `json:"CRMLogicalSystem"`
	CRMObjectUUID                  string `json:"CRMObjectUUID"`
	CRMObjectID                    string `json:"CRMObjectID"`
	CRMObjectType                  string `json:"CRMObjectType"`
	RetsMgmtItmLogProcgStatus      string `json:"RetsMgmtItmLogProcgStatus"`
	RetsMgmtItmCompnProcgStatus    string `json:"RetsMgmtItmCompnProcgStatus"`
	RetsMgmtItmProcgStatus         string `json:"RetsMgmtItmProcgStatus"`
	ReturnsDocumentStatus          string `json:"ReturnsDocumentStatus"`
	ReturnsDocumentApprovalStatus  string `json:"ReturnsDocumentApprovalStatus"`
	SDProcessStatus                string `json:"SDProcessStatus"`
	ReferenceSDDocument            string `json:"ReferenceSDDocument"`
	ReferenceSDDocumentItem        string `json:"ReferenceSDDocumentItem"`
	ReferenceSDDocumentCategory    string `json:"ReferenceSDDocumentCategory"`
	SDDocumentRejectionStatus      string `json:"SDDocumentRejectionStatus"`
	ToItemPricingElement           string `json:"to_PricingElement"`
	ToItemProcessStep              string `json:"to_ProcessStep"`
	ToItemScheduleLine             string `json:"to_ScheduleLine"`
}

type ToHeaderPartner struct {
	CustomerReturn               string `json:"CustomerReturn"`
	PartnerFunction              string `json:"PartnerFunction"`
	Customer                     string `json:"Customer"`
	Supplier                     string `json:"Supplier"`
	Personnel                    string `json:"Personnel"`
	ContactPerson                string `json:"ContactPerson"`
	BusinessPartnerAddressUUID   string `json:"BusinessPartnerAddressUUID"`
	BPRefAddrForDocSpcfcAddrUUID string `json:"BPRefAddrForDocSpcfcAddrUUID"`
}

type ToItem struct {
	CustomerReturn                 string `json:"CustomerReturn"`
	CustomerReturnItem             string `json:"CustomerReturnItem"`
	HigherLevelItem                string `json:"HigherLevelItem"`
	CustomerReturnItemCategory     string `json:"CustomerReturnItemCategory"`
	CustomerReturnItemText         string `json:"CustomerReturnItemText"`
	PurchaseOrderByCustomer        string `json:"PurchaseOrderByCustomer"`
	Material                       string `json:"Material"`
	MaterialByCustomer             string `json:"MaterialByCustomer"`
	RequestedQuantity              string `json:"RequestedQuantity"`
	RequestedQuantityUnit          string `json:"RequestedQuantityUnit"`
	ItemGrossWeight                string `json:"ItemGrossWeight"`
	ItemNetWeight                  string `json:"ItemNetWeight"`
	ItemWeightUnit                 string `json:"ItemWeightUnit"`
	ItemVolume                     string `json:"ItemVolume"`
	ItemVolumeUnit                 string `json:"ItemVolumeUnit"`
	TransactionCurrency            string `json:"TransactionCurrency"`
	NetAmount                      string `json:"NetAmount"`
	MaterialGroup                  string `json:"MaterialGroup"`
	Batch                          string `json:"Batch"`
	ProductionPlant                string `json:"ProductionPlant"`
	StorageLocation                string `json:"StorageLocation"`
	ShippingPoint                  string `json:"ShippingPoint"`
	ShippingType                   string `json:"ShippingType"`
	DeliveryPriority               string `json:"DeliveryPriority"`
	IncotermsClassification        string `json:"IncotermsClassification"`
	IncotermsTransferLocation      string `json:"IncotermsTransferLocation"`
	IncotermsLocation1             string `json:"IncotermsLocation1"`
	IncotermsLocation2             string `json:"IncotermsLocation2"`
	CustomerPaymentTerms           string `json:"CustomerPaymentTerms"`
	ProductTaxClassification1      string `json:"ProductTaxClassification1"`
	ProductTaxClassification2      string `json:"ProductTaxClassification2"`
	ProductTaxClassification3      string `json:"ProductTaxClassification3"`
	ProductTaxClassification4      string `json:"ProductTaxClassification4"`
	ProductTaxClassification5      string `json:"ProductTaxClassification5"`
	ProductTaxClassification6      string `json:"ProductTaxClassification6"`
	ProductTaxClassification7      string `json:"ProductTaxClassification7"`
	ProductTaxClassification8      string `json:"ProductTaxClassification8"`
	ProductTaxClassification9      string `json:"ProductTaxClassification9"`
	SalesDocumentRjcnReason        string `json:"SalesDocumentRjcnReason"`
	ItemBillingBlockReason         string `json:"ItemBillingBlockReason"`
	ProfitCenter                   string `json:"ProfitCenter"`
	RetsMgmtProcess                string `json:"RetsMgmtProcess"`
	RetsMgmtProcessItem            string `json:"RetsMgmtProcessItem"`
	ReturnReason                   string `json:"ReturnReason"`
	RetsMgmtProcessingBlock        string `json:"RetsMgmtProcessingBlock"`
	CustRetItmFollowUpActivity     string `json:"CustRetItmFollowUpActivity"`
	ReturnsMaterialHasBeenReceived string `json:"ReturnsMaterialHasBeenReceived"`
	ReturnsRefundType              string `json:"ReturnsRefundType"`
	ReturnsRefundProcgMode         string `json:"ReturnsRefundProcgMode"`
	ReturnsRefundExtent            string `json:"ReturnsRefundExtent"`
	PrelimRefundIsDetermined       string `json:"PrelimRefundIsDetermined"`
	ReturnsRefundRjcnReason        string `json:"ReturnsRefundRjcnReason"`
	ReplacementMaterial            string `json:"ReplacementMaterial"`
	ReplacementMaterialQuantity    string `json:"ReplacementMaterialQuantity"`
	ReplacementMaterialQtyUnit     string `json:"ReplacementMaterialQtyUnit"`
	ReplacementMaterialIsRequested string `json:"ReplacementMaterialIsRequested"`
	ReplacementMatlSupplyingPlant  string `json:"ReplacementMatlSupplyingPlant"`
	NextPlantForFollowUpActivity   string `json:"NextPlantForFollowUpActivity"`
	ReturnsTransshipmentPlant      string `json:"ReturnsTransshipmentPlant"`
	Supplier                       string `json:"Supplier"`
	SupplierRetMatlAuthzn          string `json:"SupplierRetMatlAuthzn"`
	SuplrRetMatlAuthznIsRequired   string `json:"SuplrRetMatlAuthznIsRequired"`
	CustomerRetMatlInspResultCode  string `json:"CustomerRetMatlInspResultCode"`
	NextFllwUpActivityForMatlInsp  string `json:"NextFllwUpActivityForMatlInsp"`
	RetMatlInspResultCode          string `json:"RetMatlInspResultCode"`
	ProductIsInspectedAtCustSite   string `json:"ProductIsInspectedAtCustSite"`
	CustRetMatlAuthzn              string `json:"CustRetMatlAuthzn"`
	CRMLogicalSystem               string `json:"CRMLogicalSystem"`
	CRMObjectUUID                  string `json:"CRMObjectUUID"`
	CRMObjectID                    string `json:"CRMObjectID"`
	CRMObjectType                  string `json:"CRMObjectType"`
	RetsMgmtItmLogProcgStatus      string `json:"RetsMgmtItmLogProcgStatus"`
	RetsMgmtItmCompnProcgStatus    string `json:"RetsMgmtItmCompnProcgStatus"`
	RetsMgmtItmProcgStatus         string `json:"RetsMgmtItmProcgStatus"`
	ReturnsDocumentStatus          string `json:"ReturnsDocumentStatus"`
	ReturnsDocumentApprovalStatus  string `json:"ReturnsDocumentApprovalStatus"`
	SDProcessStatus                string `json:"SDProcessStatus"`
	ReferenceSDDocument            string `json:"ReferenceSDDocument"`
	ReferenceSDDocumentItem        string `json:"ReferenceSDDocumentItem"`
	ReferenceSDDocumentCategory    string `json:"ReferenceSDDocumentCategory"`
	SDDocumentRejectionStatus      string `json:"SDDocumentRejectionStatus"`
    ToItemPricingElement           string `json:"to_PricingElement"`
	ToItemProcessStep              string `json:"to_ProcessStep"`
	ToItemScheduleLine             string `json:"to_ScheduleLine"`
}

type ToItemPricingElement struct {
	CustomerReturn                string `json:"CustomerReturn"`
	CustomerReturnItem            string `json:"CustomerReturnItem"`
	PricingProcedureStep          string `json:"PricingProcedureStep"`
	PricingProcedureCounter       string `json:"PricingProcedureCounter"`
	ConditionType                 string `json:"ConditionType"`
	PricingDateTime               string `json:"PricingDateTime"`
	ConditionCalculationType      string `json:"ConditionCalculationType"`
	ConditionBaseValue            string `json:"ConditionBaseValue"`
	ConditionRateValue            string `json:"ConditionRateValue"`
	ConditionCurrency             string `json:"ConditionCurrency"`
	ConditionQuantity             string `json:"ConditionQuantity"`
	ConditionQuantityUnit         string `json:"ConditionQuantityUnit"`
	ConditionCategory             string `json:"ConditionCategory"`
	ConditionIsForStatistics      bool   `json:"ConditionIsForStatistics"`
	PricingScaleType              string `json:"PricingScaleType"`
	IsRelevantForAccrual          bool   `json:"IsRelevantForAccrual"`
	CndnIsRelevantForInvoiceList  string `json:"CndnIsRelevantForInvoiceList"`
	ConditionOrigin               string `json:"ConditionOrigin"`
	IsGroupCondition              string `json:"IsGroupCondition"`
	ConditionRecord               string `json:"ConditionRecord"`
	ConditionSequentialNumber     string `json:"ConditionSequentialNumber"`
	TaxCode                       string `json:"TaxCode"`
	WithholdingTaxCode            string `json:"WithholdingTaxCode"`
	CndnRoundingOffDiffAmount     string `json:"CndnRoundingOffDiffAmount"`
	ConditionAmount               string `json:"ConditionAmount"`
	TransactionCurrency           string `json:"TransactionCurrency"`
	ConditionControl              string `json:"ConditionControl"`
	ConditionInactiveReason       string `json:"ConditionInactiveReason"`
	ConditionClass                string `json:"ConditionClass"`
	PrcgProcedureCounterForHeader string `json:"PrcgProcedureCounterForHeader"`
	FactorForConditionBasisValue  string `json:"FactorForConditionBasisValue"`
	StructureCondition            string `json:"StructureCondition"`
	PeriodFactorForCndnBasisValue string `json:"PeriodFactorForCndnBasisValue"`
	PricingScaleBasis             string `json:"PricingScaleBasis"`
	ConditionScaleBasisValue      string `json:"ConditionScaleBasisValue"`
	ConditionScaleBasisUnit       string `json:"ConditionScaleBasisUnit"`
	ConditionScaleBasisCurrency   string `json:"ConditionScaleBasisCurrency"`
	CndnIsRelevantForIntcoBilling bool   `json:"CndnIsRelevantForIntcoBilling"`
	ConditionIsManuallyChanged    bool   `json:"ConditionIsManuallyChanged"`
	ConditionIsForConfiguration   bool   `json:"ConditionIsForConfiguration"`
	VariantCondition              string `json:"VariantCondition"`
}

type ToItemProcessStep struct {
	RetsMgmtProcess               string `json:"RetsMgmtProcess"`
	RetsMgmtProcessItem           string `json:"RetsMgmtProcessItem"`
	RetsMgmtProcItmQtySplit       string `json:"RetsMgmtProcItmQtySplit"`
	RetsMgmtProcessStep           string `json:"RetsMgmtProcessStep"`
	ReturnsDocumentType           string `json:"ReturnsDocumentType"`
	ReturnsDocument               string `json:"ReturnsDocument"`
	ReturnsDocumentItem           string `json:"ReturnsDocumentItem"`
	ReturnsDocumentStatus         string `json:"ReturnsDocumentStatus"`
	ReturnsDocumentApprovalStatus string `json:"ReturnsDocumentApprovalStatus"`
	ReturnsReferenceDocumentType  string `json:"ReturnsReferenceDocumentType"`
	ReturnsReferenceDocument      string `json:"ReturnsReferenceDocument"`
	ReturnsReferenceDocumentItem  string `json:"ReturnsReferenceDocumentItem"`
	RetsMgmtProcStepExecStatus    string `json:"RetsMgmtProcStepExecStatus"`
}

type ToItemScheduleLine struct {
	CustomerReturn                string `json:"CustomerReturn"`
	CustomerReturnItem            string `json:"CustomerReturnItem"`
	ScheduleLine                  string `json:"ScheduleLine"`
	OrderQuantityUnit             string `json:"OrderQuantityUnit"`
	ConfdOrderQtyByMatlAvailCheck string `json:"ConfdOrderQtyByMatlAvailCheck"`
	DeliveredQtyInOrderQtyUnit    string `json:"DeliveredQtyInOrderQtyUnit"`
	OpenConfdDelivQtyInOrdQtyUnit string `json:"OpenConfdDelivQtyInOrdQtyUnit"`
	DelivBlockReasonForSchedLine  string `json:"DelivBlockReasonForSchedLine"`
}
